name: Linux Container Node Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          PRUEBA: ${{ secrets.PRUEBA }}
      - uses: azure/docker-login@v1
        with:
          login-server: containerregistrytestinter.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t containerregistrytestinter.azurecr.io/testwebappdockercontainer:${{ github.sha }}
          docker push containerregistrytestinter.azurecr.io/testwebappdockercontainer:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'TestWebAppDockerContainer'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'containerregistrytestinter.azurecr.io/testwebappdockercontainer:${{ github.sha }}'
